# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crypto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'crypto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63rypto.proto\x12\x0erpc_info.proto\"\xb4\x02\n\x06\x43rypto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\x12\x15\n\rcurrent_price\x18\x05 \x01(\x01\x12\x12\n\nmarket_cap\x18\x06 \x01(\x03\x12\x17\n\x0fmarket_cap_rank\x18\x07 \x01(\x05\x12\x1f\n\x17\x66ully_diluted_valuation\x18\x08 \x01(\x03\x12\x14\n\x0ctotal_volume\x18\t \x01(\x03\x12\x10\n\x08high_24h\x18\n \x01(\x01\x12\x0f\n\x07low_24h\x18\x0b \x01(\x01\x12\x18\n\x10price_change_24h\x18\x0c \x01(\x01\x12#\n\x1bprice_change_percentage_24h\x18\r \x01(\x01\x12\x14\n\x0clast_updated\x18\x0e \x01(\t\"3\n\rCryptoRequest\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"5\n\nCryptoList\x12\'\n\x07\x63ryptos\x18\x01 \x03(\x0b\x32\x16.rpc_info.proto.Crypto\"1\n\x11\x43ryptoByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t2\xa7\x01\n\rCryptoService\x12J\n\rGetTopCryptos\x12\x1d.rpc_info.proto.CryptoRequest\x1a\x1a.rpc_info.proto.CryptoList\x12J\n\rGetCryptoById\x12!.rpc_info.proto.CryptoByIdRequest\x1a\x16.rpc_info.proto.Cryptob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crypto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRYPTO']._serialized_start=33
  _globals['_CRYPTO']._serialized_end=341
  _globals['_CRYPTOREQUEST']._serialized_start=343
  _globals['_CRYPTOREQUEST']._serialized_end=394
  _globals['_CRYPTOLIST']._serialized_start=396
  _globals['_CRYPTOLIST']._serialized_end=449
  _globals['_CRYPTOBYIDREQUEST']._serialized_start=451
  _globals['_CRYPTOBYIDREQUEST']._serialized_end=500
  _globals['_CRYPTOSERVICE']._serialized_start=503
  _globals['_CRYPTOSERVICE']._serialized_end=670
# @@protoc_insertion_point(module_scope)
